trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'

- script: npm install
  displayName: Install Dependencies

- script: npx playwright install --with-deps
  displayName: Install Browsers

- script: npx playwright test
  displayName: Run Playwright Tests